spring.application.name=recebivel-api

spring.datasource.url=jdbc:postgresql://localhost:5432/recebivel
spring.datasource.username=recebivel
spring.datasource.password=recebivel

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.flyway.enabled=true