spring.datasource.url=jdbc:postgresql://localhost:5432/recebivel
spring.datasource.username=recebivel
spring.datasource.password=recebivel

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.flyway.enabled=true

jwt.secret=recebivel-api-chave-secreta-local-para-desenvolvimento
jwt.expiration=86400000